
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OD_3_0_H
#define OD_3_0_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 OD_3_0_valueRangeTest (UNS8 typeValue, void * value);
const indextable * OD_3_0_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data OD_3_0_Data;
extern UNS8 OD_3_0_trashvariables_TRASH1;		/* Mapped at index 0x2000, subindex 0x01 */
extern UNS8 OD_3_0_trashvariables_TRASH8;		/* Mapped at index 0x2000, subindex 0x02 */
extern UNS16 OD_3_0_trashvariables_TRASH16;		/* Mapped at index 0x2000, subindex 0x03 */
extern UNS32 OD_3_0_trashvariables_TRASH32;		/* Mapped at index 0x2000, subindex 0x04 */
extern UNS64 OD_3_0_trashvariables_TRASH64;		/* Mapped at index 0x2000, subindex 0x05 */

#endif // OD_3_0_H
