
/* File generated by gen_cfile.py. Should not be modified. */

#include "OD_3_0.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 OD_3_0_trashvariables_TRASH1 = 0x0;		/* Mapped at index 0x2000, subindex 0x01 */
UNS8 OD_3_0_trashvariables_TRASH8 = 0x0;		/* Mapped at index 0x2000, subindex 0x02 */
UNS16 OD_3_0_trashvariables_TRASH16 = 0x0;		/* Mapped at index 0x2000, subindex 0x03 */
UNS32 OD_3_0_trashvariables_TRASH32 = 0x0;		/* Mapped at index 0x2000, subindex 0x04 */
UNS64 OD_3_0_trashvariables_TRASH64 = 0x0;		/* Mapped at index 0x2000, subindex 0x05 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 OD_3_0_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 OD_3_0_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 OD_3_0_iam_a_slave = 0;

TIMER_HANDLE OD_3_0_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 OD_3_0_obj1000 = 0x0;	/* 0 */
                    subindex OD_3_0_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&OD_3_0_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 OD_3_0_obj1001 = 0x0;	/* 0 */
                    subindex OD_3_0_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_3_0_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 OD_3_0_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 OD_3_0_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t OD_3_0_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex OD_3_0_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&OD_3_0_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_3_0_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 OD_3_0_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 OD_3_0_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 OD_3_0_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 OD_3_0_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 OD_3_0_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 OD_3_0_highestSubIndex_obj1016 = 0;
                    UNS32 OD_3_0_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 OD_3_0_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 OD_3_0_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 OD_3_0_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 OD_3_0_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 OD_3_0_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 OD_3_0_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex OD_3_0_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_3_0_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_3_0_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_3_0_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_3_0_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_3_0_obj1018_Serial_Number }
                     };

/* index 0x1F22 :   Concise DCF. */
                    UNS8 OD_3_0_highestSubIndex_obj1F22 = 127; /* number of subindex - 1*/
                    UNS8* OD_3_0_obj1F22[] = 
                    {
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)"",
                      (UNS8*)""
                    };
                    subindex OD_3_0_Index1F22[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_3_0_highestSubIndex_obj1F22 },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[0] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[1] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[2] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[3] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[4] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[5] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[6] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[7] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[8] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[9] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[10] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[11] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[12] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[13] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[14] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[15] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[16] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[17] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[18] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[19] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[20] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[21] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[22] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[23] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[24] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[25] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[26] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[27] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[28] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[29] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[30] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[31] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[32] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[33] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[34] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[35] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[36] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[37] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[38] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[39] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[40] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[41] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[42] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[43] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[44] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[45] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[46] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[47] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[48] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[49] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[50] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[51] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[52] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[53] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[54] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[55] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[56] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[57] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[58] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[59] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[60] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[61] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[62] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[63] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[64] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[65] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[66] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[67] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[68] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[69] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[70] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[71] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[72] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[73] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[74] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[75] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[76] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[77] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[78] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[79] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[80] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[81] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[82] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[83] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[84] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[85] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[86] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[87] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[88] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[89] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[90] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[91] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[92] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[93] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[94] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[95] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[96] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[97] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[98] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[99] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[100] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[101] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[102] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[103] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[104] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[105] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[106] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[107] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[108] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[109] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[110] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[111] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[112] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[113] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[114] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[115] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[116] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[117] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[118] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[119] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[120] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[121] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[122] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[123] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[124] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[125] },
                       { RW, domain, 0, (void*)&OD_3_0_obj1F22[126] }
                     };

/* index 0x2000 :   Mapped variable OD_3_0_trashvariables */
                    UNS8 OD_3_0_highestSubIndex_obj2000 = 5; /* number of subindex - 1*/
                    subindex OD_3_0_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_3_0_highestSubIndex_obj2000 },
                       { RW, boolean, sizeof (UNS8), (void*)&OD_3_0_trashvariables_TRASH1 },
                       { RW, uint8, sizeof (UNS8), (void*)&OD_3_0_trashvariables_TRASH8 },
                       { RW, uint16, sizeof (UNS16), (void*)&OD_3_0_trashvariables_TRASH16 },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_3_0_trashvariables_TRASH32 },
                       { RW, uint64, sizeof (UNS64), (void*)&OD_3_0_trashvariables_TRASH64 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable OD_3_0_objdict[] = 
{
  { (subindex*)OD_3_0_Index1000,sizeof(OD_3_0_Index1000)/sizeof(OD_3_0_Index1000[0]), 0x1000},
  { (subindex*)OD_3_0_Index1001,sizeof(OD_3_0_Index1001)/sizeof(OD_3_0_Index1001[0]), 0x1001},
  { (subindex*)OD_3_0_Index1018,sizeof(OD_3_0_Index1018)/sizeof(OD_3_0_Index1018[0]), 0x1018},
  { (subindex*)OD_3_0_Index1F22,sizeof(OD_3_0_Index1F22)/sizeof(OD_3_0_Index1F22[0]), 0x1F22},
  { (subindex*)OD_3_0_Index2000,sizeof(OD_3_0_Index2000)/sizeof(OD_3_0_Index2000[0]), 0x2000},
};

const indextable * OD_3_0_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1018: i = 2;break;
		case 0x1F22: i = 3;break;
		case 0x2000: i = 4;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &OD_3_0_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status OD_3_0_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index OD_3_0_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index OD_3_0_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 OD_3_0_ObjdictSize = sizeof(OD_3_0_objdict)/sizeof(OD_3_0_objdict[0]); 

CO_Data OD_3_0_Data = CANOPEN_NODE_DATA_INITIALIZER(OD_3_0);

