#!/usr/bin/env python
# -*- coding: utf-8 -*-
## Code generated by Beremiz python mixin confnode
##

## Code for PLC global variable access
from targets.typemapping import TypeTranslator
import ctypes
_py_ext_0GlobalsDesc = []
__ext_name__ = "py_ext_0"
PLCGlobalsDesc.append(( "py_ext_0" , _py_ext_0GlobalsDesc ))
_debug_ctype, _debug_unpack, _debug_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_debug = PLCBinary.__SafeGetPLCGlob_debug
_PySafeGetPLCGlob_debug.restype = None
_PySafeGetPLCGlob_debug.argtypes = [ctypes.POINTER(_debug_ctype)]
_PySafeSetPLCGlob_debug = PLCBinary.__SafeSetPLCGlob_debug
_PySafeSetPLCGlob_debug.restype = None
_PySafeSetPLCGlob_debug.argtypes = [ctypes.POINTER(_debug_ctype)]
_py_ext_0GlobalsDesc.append((
    "debug",
    "INT",
    'Print Debug 1:info+warning+error, 2:warning+error, 3:error, 4:none',
    None,
    u''))

_PATH_ctype, _PATH_unpack, _PATH_pack = \
    TypeTranslator["STRING"]
_PySafeGetPLCGlob_PATH = PLCBinary.__SafeGetPLCGlob_PATH
_PySafeGetPLCGlob_PATH.restype = None
_PySafeGetPLCGlob_PATH.argtypes = [ctypes.POINTER(_PATH_ctype)]
_PySafeSetPLCGlob_PATH = PLCBinary.__SafeSetPLCGlob_PATH
_PySafeSetPLCGlob_PATH.restype = None
_PySafeSetPLCGlob_PATH.argtypes = [ctypes.POINTER(_PATH_ctype)]
_py_ext_0GlobalsDesc.append((
    "PATH",
    "STRING",
    'PATH to Source file',
    None,
    u''))

_Grumpf_ctype, _Grumpf_unpack, _Grumpf_pack = \
    TypeTranslator["STRING"]
_PySafeGetPLCGlob_Grumpf = PLCBinary.__SafeGetPLCGlob_Grumpf
_PySafeGetPLCGlob_Grumpf.restype = None
_PySafeGetPLCGlob_Grumpf.argtypes = [ctypes.POINTER(_Grumpf_ctype)]
_PySafeSetPLCGlob_Grumpf = PLCBinary.__SafeSetPLCGlob_Grumpf
_PySafeSetPLCGlob_Grumpf.restype = None
_PySafeSetPLCGlob_Grumpf.argtypes = [ctypes.POINTER(_Grumpf_ctype)]
_py_ext_0GlobalsDesc.append((
    "Grumpf",
    "STRING",
    u'',
    None,
    u''))

_i_status_ctype, _i_status_unpack, _i_status_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_i_status = PLCBinary.__SafeGetPLCGlob_i_status
_PySafeGetPLCGlob_i_status.restype = None
_PySafeGetPLCGlob_i_status.argtypes = [ctypes.POINTER(_i_status_ctype)]
_PySafeSetPLCGlob_i_status = PLCBinary.__SafeSetPLCGlob_i_status
_PySafeSetPLCGlob_i_status.restype = None
_PySafeSetPLCGlob_i_status.argtypes = [ctypes.POINTER(_i_status_ctype)]
_py_ext_0GlobalsDesc.append((
    "i_status",
    "INT",
    'Error Code readSignal',
    None,
    u''))

_i_status_CSV_ctype, _i_status_CSV_unpack, _i_status_CSV_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_i_status_CSV = PLCBinary.__SafeGetPLCGlob_i_status_CSV
_PySafeGetPLCGlob_i_status_CSV.restype = None
_PySafeGetPLCGlob_i_status_CSV.argtypes = [ctypes.POINTER(_i_status_CSV_ctype)]
_PySafeSetPLCGlob_i_status_CSV = PLCBinary.__SafeSetPLCGlob_i_status_CSV
_PySafeSetPLCGlob_i_status_CSV.restype = None
_PySafeSetPLCGlob_i_status_CSV.argtypes = [ctypes.POINTER(_i_status_CSV_ctype)]
_py_ext_0GlobalsDesc.append((
    "i_status_CSV",
    "INT",
    'Error Code readSignalCSV',
    None,
    u''))

_NameFile_ctype, _NameFile_unpack, _NameFile_pack = \
    TypeTranslator["STRING"]
_PySafeGetPLCGlob_NameFile = PLCBinary.__SafeGetPLCGlob_NameFile
_PySafeGetPLCGlob_NameFile.restype = None
_PySafeGetPLCGlob_NameFile.argtypes = [ctypes.POINTER(_NameFile_ctype)]
_PySafeSetPLCGlob_NameFile = PLCBinary.__SafeSetPLCGlob_NameFile
_PySafeSetPLCGlob_NameFile.restype = None
_PySafeSetPLCGlob_NameFile.argtypes = [ctypes.POINTER(_NameFile_ctype)]
_py_ext_0GlobalsDesc.append((
    "NameFile",
    "STRING",
    'File data',
    None,
    u''))

_NameFileCSV_ctype, _NameFileCSV_unpack, _NameFileCSV_pack = \
    TypeTranslator["STRING"]
_PySafeGetPLCGlob_NameFileCSV = PLCBinary.__SafeGetPLCGlob_NameFileCSV
_PySafeGetPLCGlob_NameFileCSV.restype = None
_PySafeGetPLCGlob_NameFileCSV.argtypes = [ctypes.POINTER(_NameFileCSV_ctype)]
_PySafeSetPLCGlob_NameFileCSV = PLCBinary.__SafeSetPLCGlob_NameFileCSV
_PySafeSetPLCGlob_NameFileCSV.restype = None
_PySafeSetPLCGlob_NameFileCSV.argtypes = [ctypes.POINTER(_NameFileCSV_ctype)]
_py_ext_0GlobalsDesc.append((
    "NameFileCSV",
    "STRING",
    'File data',
    None,
    u''))

_WRITE_OK_ctype, _WRITE_OK_unpack, _WRITE_OK_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_WRITE_OK = PLCBinary.__SafeGetPLCGlob_WRITE_OK
_PySafeGetPLCGlob_WRITE_OK.restype = None
_PySafeGetPLCGlob_WRITE_OK.argtypes = [ctypes.POINTER(_WRITE_OK_ctype)]
_PySafeSetPLCGlob_WRITE_OK = PLCBinary.__SafeSetPLCGlob_WRITE_OK
_PySafeSetPLCGlob_WRITE_OK.restype = None
_PySafeSetPLCGlob_WRITE_OK.argtypes = [ctypes.POINTER(_WRITE_OK_ctype)]
_py_ext_0GlobalsDesc.append((
    "WRITE_OK",
    "INT",
    '5-level',
    None,
    u''))

_WRITE_FAIL_ctype, _WRITE_FAIL_unpack, _WRITE_FAIL_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_WRITE_FAIL = PLCBinary.__SafeGetPLCGlob_WRITE_FAIL
_PySafeGetPLCGlob_WRITE_FAIL.restype = None
_PySafeGetPLCGlob_WRITE_FAIL.argtypes = [ctypes.POINTER(_WRITE_FAIL_ctype)]
_PySafeSetPLCGlob_WRITE_FAIL = PLCBinary.__SafeSetPLCGlob_WRITE_FAIL
_PySafeSetPLCGlob_WRITE_FAIL.restype = None
_PySafeSetPLCGlob_WRITE_FAIL.argtypes = [ctypes.POINTER(_WRITE_FAIL_ctype)]
_py_ext_0GlobalsDesc.append((
    "WRITE_FAIL",
    "INT",
    '5-level',
    None,
    u''))

_READ_OK_ctype, _READ_OK_unpack, _READ_OK_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_READ_OK = PLCBinary.__SafeGetPLCGlob_READ_OK
_PySafeGetPLCGlob_READ_OK.restype = None
_PySafeGetPLCGlob_READ_OK.argtypes = [ctypes.POINTER(_READ_OK_ctype)]
_PySafeSetPLCGlob_READ_OK = PLCBinary.__SafeSetPLCGlob_READ_OK
_PySafeSetPLCGlob_READ_OK.restype = None
_PySafeSetPLCGlob_READ_OK.argtypes = [ctypes.POINTER(_READ_OK_ctype)]
_py_ext_0GlobalsDesc.append((
    "READ_OK",
    "INT",
    '4-level',
    None,
    u''))

_READ_FAIL_ctype, _READ_FAIL_unpack, _READ_FAIL_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_READ_FAIL = PLCBinary.__SafeGetPLCGlob_READ_FAIL
_PySafeGetPLCGlob_READ_FAIL.restype = None
_PySafeGetPLCGlob_READ_FAIL.argtypes = [ctypes.POINTER(_READ_FAIL_ctype)]
_PySafeSetPLCGlob_READ_FAIL = PLCBinary.__SafeSetPLCGlob_READ_FAIL
_PySafeSetPLCGlob_READ_FAIL.restype = None
_PySafeSetPLCGlob_READ_FAIL.argtypes = [ctypes.POINTER(_READ_FAIL_ctype)]
_py_ext_0GlobalsDesc.append((
    "READ_FAIL",
    "INT",
    '4-level',
    None,
    u''))

_NEXT_OK_ctype, _NEXT_OK_unpack, _NEXT_OK_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_NEXT_OK = PLCBinary.__SafeGetPLCGlob_NEXT_OK
_PySafeGetPLCGlob_NEXT_OK.restype = None
_PySafeGetPLCGlob_NEXT_OK.argtypes = [ctypes.POINTER(_NEXT_OK_ctype)]
_PySafeSetPLCGlob_NEXT_OK = PLCBinary.__SafeSetPLCGlob_NEXT_OK
_PySafeSetPLCGlob_NEXT_OK.restype = None
_PySafeSetPLCGlob_NEXT_OK.argtypes = [ctypes.POINTER(_NEXT_OK_ctype)]
_py_ext_0GlobalsDesc.append((
    "NEXT_OK",
    "INT",
    '3-level',
    None,
    u''))

_NEXT_FAIL_ctype, _NEXT_FAIL_unpack, _NEXT_FAIL_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_NEXT_FAIL = PLCBinary.__SafeGetPLCGlob_NEXT_FAIL
_PySafeGetPLCGlob_NEXT_FAIL.restype = None
_PySafeGetPLCGlob_NEXT_FAIL.argtypes = [ctypes.POINTER(_NEXT_FAIL_ctype)]
_PySafeSetPLCGlob_NEXT_FAIL = PLCBinary.__SafeSetPLCGlob_NEXT_FAIL
_PySafeSetPLCGlob_NEXT_FAIL.restype = None
_PySafeSetPLCGlob_NEXT_FAIL.argtypes = [ctypes.POINTER(_NEXT_FAIL_ctype)]
_py_ext_0GlobalsDesc.append((
    "NEXT_FAIL",
    "INT",
    '3-level',
    None,
    u''))

_OPEN_DICT_OK_ctype, _OPEN_DICT_OK_unpack, _OPEN_DICT_OK_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_OPEN_DICT_OK = PLCBinary.__SafeGetPLCGlob_OPEN_DICT_OK
_PySafeGetPLCGlob_OPEN_DICT_OK.restype = None
_PySafeGetPLCGlob_OPEN_DICT_OK.argtypes = [ctypes.POINTER(_OPEN_DICT_OK_ctype)]
_PySafeSetPLCGlob_OPEN_DICT_OK = PLCBinary.__SafeSetPLCGlob_OPEN_DICT_OK
_PySafeSetPLCGlob_OPEN_DICT_OK.restype = None
_PySafeSetPLCGlob_OPEN_DICT_OK.argtypes = [ctypes.POINTER(_OPEN_DICT_OK_ctype)]
_py_ext_0GlobalsDesc.append((
    "OPEN_DICT_OK",
    "INT",
    '2-level',
    None,
    u''))

_OPEN_DICT_FAIL_ctype, _OPEN_DICT_FAIL_unpack, _OPEN_DICT_FAIL_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_OPEN_DICT_FAIL = PLCBinary.__SafeGetPLCGlob_OPEN_DICT_FAIL
_PySafeGetPLCGlob_OPEN_DICT_FAIL.restype = None
_PySafeGetPLCGlob_OPEN_DICT_FAIL.argtypes = [ctypes.POINTER(_OPEN_DICT_FAIL_ctype)]
_PySafeSetPLCGlob_OPEN_DICT_FAIL = PLCBinary.__SafeSetPLCGlob_OPEN_DICT_FAIL
_PySafeSetPLCGlob_OPEN_DICT_FAIL.restype = None
_PySafeSetPLCGlob_OPEN_DICT_FAIL.argtypes = [ctypes.POINTER(_OPEN_DICT_FAIL_ctype)]
_py_ext_0GlobalsDesc.append((
    "OPEN_DICT_FAIL",
    "INT",
    '2-level',
    None,
    u''))

_OPEN_CSV_OK_ctype, _OPEN_CSV_OK_unpack, _OPEN_CSV_OK_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_OPEN_CSV_OK = PLCBinary.__SafeGetPLCGlob_OPEN_CSV_OK
_PySafeGetPLCGlob_OPEN_CSV_OK.restype = None
_PySafeGetPLCGlob_OPEN_CSV_OK.argtypes = [ctypes.POINTER(_OPEN_CSV_OK_ctype)]
_PySafeSetPLCGlob_OPEN_CSV_OK = PLCBinary.__SafeSetPLCGlob_OPEN_CSV_OK
_PySafeSetPLCGlob_OPEN_CSV_OK.restype = None
_PySafeSetPLCGlob_OPEN_CSV_OK.argtypes = [ctypes.POINTER(_OPEN_CSV_OK_ctype)]
_py_ext_0GlobalsDesc.append((
    "OPEN_CSV_OK",
    "INT",
    '1-level',
    None,
    u''))

_OPEN_CSV_FAIL_ctype, _OPEN_CSV_FAIL_unpack, _OPEN_CSV_FAIL_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_OPEN_CSV_FAIL = PLCBinary.__SafeGetPLCGlob_OPEN_CSV_FAIL
_PySafeGetPLCGlob_OPEN_CSV_FAIL.restype = None
_PySafeGetPLCGlob_OPEN_CSV_FAIL.argtypes = [ctypes.POINTER(_OPEN_CSV_FAIL_ctype)]
_PySafeSetPLCGlob_OPEN_CSV_FAIL = PLCBinary.__SafeSetPLCGlob_OPEN_CSV_FAIL
_PySafeSetPLCGlob_OPEN_CSV_FAIL.restype = None
_PySafeSetPLCGlob_OPEN_CSV_FAIL.argtypes = [ctypes.POINTER(_OPEN_CSV_FAIL_ctype)]
_py_ext_0GlobalsDesc.append((
    "OPEN_CSV_FAIL",
    "INT",
    '1-level',
    None,
    u''))

_UPDATE_OK_ctype, _UPDATE_OK_unpack, _UPDATE_OK_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_UPDATE_OK = PLCBinary.__SafeGetPLCGlob_UPDATE_OK
_PySafeGetPLCGlob_UPDATE_OK.restype = None
_PySafeGetPLCGlob_UPDATE_OK.argtypes = [ctypes.POINTER(_UPDATE_OK_ctype)]
_PySafeSetPLCGlob_UPDATE_OK = PLCBinary.__SafeSetPLCGlob_UPDATE_OK
_PySafeSetPLCGlob_UPDATE_OK.restype = None
_PySafeSetPLCGlob_UPDATE_OK.argtypes = [ctypes.POINTER(_UPDATE_OK_ctype)]
_py_ext_0GlobalsDesc.append((
    "UPDATE_OK",
    "INT",
    u'',
    None,
    u''))

_FILE_EOF_ctype, _FILE_EOF_unpack, _FILE_EOF_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_FILE_EOF = PLCBinary.__SafeGetPLCGlob_FILE_EOF
_PySafeGetPLCGlob_FILE_EOF.restype = None
_PySafeGetPLCGlob_FILE_EOF.argtypes = [ctypes.POINTER(_FILE_EOF_ctype)]
_PySafeSetPLCGlob_FILE_EOF = PLCBinary.__SafeSetPLCGlob_FILE_EOF
_PySafeSetPLCGlob_FILE_EOF.restype = None
_PySafeSetPLCGlob_FILE_EOF.argtypes = [ctypes.POINTER(_FILE_EOF_ctype)]
_py_ext_0GlobalsDesc.append((
    "FILE_EOF",
    "INT",
    'End of file',
    None,
    u''))

_UPDATE_FAIL_ctype, _UPDATE_FAIL_unpack, _UPDATE_FAIL_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_UPDATE_FAIL = PLCBinary.__SafeGetPLCGlob_UPDATE_FAIL
_PySafeGetPLCGlob_UPDATE_FAIL.restype = None
_PySafeGetPLCGlob_UPDATE_FAIL.argtypes = [ctypes.POINTER(_UPDATE_FAIL_ctype)]
_PySafeSetPLCGlob_UPDATE_FAIL = PLCBinary.__SafeSetPLCGlob_UPDATE_FAIL
_PySafeSetPLCGlob_UPDATE_FAIL.restype = None
_PySafeSetPLCGlob_UPDATE_FAIL.argtypes = [ctypes.POINTER(_UPDATE_FAIL_ctype)]
_py_ext_0GlobalsDesc.append((
    "UPDATE_FAIL",
    "INT",
    u'',
    None,
    u''))

_SET_VAL_OK_ctype, _SET_VAL_OK_unpack, _SET_VAL_OK_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_SET_VAL_OK = PLCBinary.__SafeGetPLCGlob_SET_VAL_OK
_PySafeGetPLCGlob_SET_VAL_OK.restype = None
_PySafeGetPLCGlob_SET_VAL_OK.argtypes = [ctypes.POINTER(_SET_VAL_OK_ctype)]
_PySafeSetPLCGlob_SET_VAL_OK = PLCBinary.__SafeSetPLCGlob_SET_VAL_OK
_PySafeSetPLCGlob_SET_VAL_OK.restype = None
_PySafeSetPLCGlob_SET_VAL_OK.argtypes = [ctypes.POINTER(_SET_VAL_OK_ctype)]
_py_ext_0GlobalsDesc.append((
    "SET_VAL_OK",
    "INT",
    u'',
    None,
    u''))

_SET_VAL_FAIL_ctype, _SET_VAL_FAIL_unpack, _SET_VAL_FAIL_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_SET_VAL_FAIL = PLCBinary.__SafeGetPLCGlob_SET_VAL_FAIL
_PySafeGetPLCGlob_SET_VAL_FAIL.restype = None
_PySafeGetPLCGlob_SET_VAL_FAIL.argtypes = [ctypes.POINTER(_SET_VAL_FAIL_ctype)]
_PySafeSetPLCGlob_SET_VAL_FAIL = PLCBinary.__SafeSetPLCGlob_SET_VAL_FAIL
_PySafeSetPLCGlob_SET_VAL_FAIL.restype = None
_PySafeSetPLCGlob_SET_VAL_FAIL.argtypes = [ctypes.POINTER(_SET_VAL_FAIL_ctype)]
_py_ext_0GlobalsDesc.append((
    "SET_VAL_FAIL",
    "INT",
    u'',
    None,
    u''))

_FILE_NOT_FOUND_ctype, _FILE_NOT_FOUND_unpack, _FILE_NOT_FOUND_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_FILE_NOT_FOUND = PLCBinary.__SafeGetPLCGlob_FILE_NOT_FOUND
_PySafeGetPLCGlob_FILE_NOT_FOUND.restype = None
_PySafeGetPLCGlob_FILE_NOT_FOUND.argtypes = [ctypes.POINTER(_FILE_NOT_FOUND_ctype)]
_PySafeSetPLCGlob_FILE_NOT_FOUND = PLCBinary.__SafeSetPLCGlob_FILE_NOT_FOUND
_PySafeSetPLCGlob_FILE_NOT_FOUND.restype = None
_PySafeSetPLCGlob_FILE_NOT_FOUND.argtypes = [ctypes.POINTER(_FILE_NOT_FOUND_ctype)]
_py_ext_0GlobalsDesc.append((
    "FILE_NOT_FOUND",
    "INT",
    u'',
    None,
    u''))

_CLOSE_CSV_OK_ctype, _CLOSE_CSV_OK_unpack, _CLOSE_CSV_OK_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_CLOSE_CSV_OK = PLCBinary.__SafeGetPLCGlob_CLOSE_CSV_OK
_PySafeGetPLCGlob_CLOSE_CSV_OK.restype = None
_PySafeGetPLCGlob_CLOSE_CSV_OK.argtypes = [ctypes.POINTER(_CLOSE_CSV_OK_ctype)]
_PySafeSetPLCGlob_CLOSE_CSV_OK = PLCBinary.__SafeSetPLCGlob_CLOSE_CSV_OK
_PySafeSetPLCGlob_CLOSE_CSV_OK.restype = None
_PySafeSetPLCGlob_CLOSE_CSV_OK.argtypes = [ctypes.POINTER(_CLOSE_CSV_OK_ctype)]
_py_ext_0GlobalsDesc.append((
    "CLOSE_CSV_OK",
    "INT",
    u'',
    None,
    u''))

_CLOSE_CSV_FAIL_ctype, _CLOSE_CSV_FAIL_unpack, _CLOSE_CSV_FAIL_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_CLOSE_CSV_FAIL = PLCBinary.__SafeGetPLCGlob_CLOSE_CSV_FAIL
_PySafeGetPLCGlob_CLOSE_CSV_FAIL.restype = None
_PySafeGetPLCGlob_CLOSE_CSV_FAIL.argtypes = [ctypes.POINTER(_CLOSE_CSV_FAIL_ctype)]
_PySafeSetPLCGlob_CLOSE_CSV_FAIL = PLCBinary.__SafeSetPLCGlob_CLOSE_CSV_FAIL
_PySafeSetPLCGlob_CLOSE_CSV_FAIL.restype = None
_PySafeSetPLCGlob_CLOSE_CSV_FAIL.argtypes = [ctypes.POINTER(_CLOSE_CSV_FAIL_ctype)]
_py_ext_0GlobalsDesc.append((
    "CLOSE_CSV_FAIL",
    "INT",
    u'',
    None,
    u''))

_SAVE_CSV_OK_ctype, _SAVE_CSV_OK_unpack, _SAVE_CSV_OK_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_SAVE_CSV_OK = PLCBinary.__SafeGetPLCGlob_SAVE_CSV_OK
_PySafeGetPLCGlob_SAVE_CSV_OK.restype = None
_PySafeGetPLCGlob_SAVE_CSV_OK.argtypes = [ctypes.POINTER(_SAVE_CSV_OK_ctype)]
_PySafeSetPLCGlob_SAVE_CSV_OK = PLCBinary.__SafeSetPLCGlob_SAVE_CSV_OK
_PySafeSetPLCGlob_SAVE_CSV_OK.restype = None
_PySafeSetPLCGlob_SAVE_CSV_OK.argtypes = [ctypes.POINTER(_SAVE_CSV_OK_ctype)]
_py_ext_0GlobalsDesc.append((
    "SAVE_CSV_OK",
    "INT",
    u'',
    None,
    u''))

_SAVE_CSV_FAIL_ctype, _SAVE_CSV_FAIL_unpack, _SAVE_CSV_FAIL_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_SAVE_CSV_FAIL = PLCBinary.__SafeGetPLCGlob_SAVE_CSV_FAIL
_PySafeGetPLCGlob_SAVE_CSV_FAIL.restype = None
_PySafeGetPLCGlob_SAVE_CSV_FAIL.argtypes = [ctypes.POINTER(_SAVE_CSV_FAIL_ctype)]
_PySafeSetPLCGlob_SAVE_CSV_FAIL = PLCBinary.__SafeSetPLCGlob_SAVE_CSV_FAIL
_PySafeSetPLCGlob_SAVE_CSV_FAIL.restype = None
_PySafeSetPLCGlob_SAVE_CSV_FAIL.argtypes = [ctypes.POINTER(_SAVE_CSV_FAIL_ctype)]
_py_ext_0GlobalsDesc.append((
    "SAVE_CSV_FAIL",
    "INT",
    u'',
    None,
    u''))

_SIGNAL_NOT_CONNECT_ctype, _SIGNAL_NOT_CONNECT_unpack, _SIGNAL_NOT_CONNECT_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_SIGNAL_NOT_CONNECT = PLCBinary.__SafeGetPLCGlob_SIGNAL_NOT_CONNECT
_PySafeGetPLCGlob_SIGNAL_NOT_CONNECT.restype = None
_PySafeGetPLCGlob_SIGNAL_NOT_CONNECT.argtypes = [ctypes.POINTER(_SIGNAL_NOT_CONNECT_ctype)]
_PySafeSetPLCGlob_SIGNAL_NOT_CONNECT = PLCBinary.__SafeSetPLCGlob_SIGNAL_NOT_CONNECT
_PySafeSetPLCGlob_SIGNAL_NOT_CONNECT.restype = None
_PySafeSetPLCGlob_SIGNAL_NOT_CONNECT.argtypes = [ctypes.POINTER(_SIGNAL_NOT_CONNECT_ctype)]
_py_ext_0GlobalsDesc.append((
    "SIGNAL_NOT_CONNECT",
    "INT",
    u'',
    None,
    u''))

_INFO_ctype, _INFO_unpack, _INFO_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_INFO = PLCBinary.__SafeGetPLCGlob_INFO
_PySafeGetPLCGlob_INFO.restype = None
_PySafeGetPLCGlob_INFO.argtypes = [ctypes.POINTER(_INFO_ctype)]
_PySafeSetPLCGlob_INFO = PLCBinary.__SafeSetPLCGlob_INFO
_PySafeSetPLCGlob_INFO.restype = None
_PySafeSetPLCGlob_INFO.argtypes = [ctypes.POINTER(_INFO_ctype)]
_py_ext_0GlobalsDesc.append((
    "INFO",
    "INT",
    'Debug message level',
    None,
    u''))

_WARNING_ctype, _WARNING_unpack, _WARNING_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_WARNING = PLCBinary.__SafeGetPLCGlob_WARNING
_PySafeGetPLCGlob_WARNING.restype = None
_PySafeGetPLCGlob_WARNING.argtypes = [ctypes.POINTER(_WARNING_ctype)]
_PySafeSetPLCGlob_WARNING = PLCBinary.__SafeSetPLCGlob_WARNING
_PySafeSetPLCGlob_WARNING.restype = None
_PySafeSetPLCGlob_WARNING.argtypes = [ctypes.POINTER(_WARNING_ctype)]
_py_ext_0GlobalsDesc.append((
    "WARNING",
    "INT",
    'Debug message level',
    None,
    u''))

_ERROR_ctype, _ERROR_unpack, _ERROR_pack = \
    TypeTranslator["INT"]
_PySafeGetPLCGlob_ERROR = PLCBinary.__SafeGetPLCGlob_ERROR
_PySafeGetPLCGlob_ERROR.restype = None
_PySafeGetPLCGlob_ERROR.argtypes = [ctypes.POINTER(_ERROR_ctype)]
_PySafeSetPLCGlob_ERROR = PLCBinary.__SafeSetPLCGlob_ERROR
_PySafeSetPLCGlob_ERROR.restype = None
_PySafeSetPLCGlob_ERROR.argtypes = [ctypes.POINTER(_ERROR_ctype)]
_py_ext_0GlobalsDesc.append((
    "ERROR",
    "INT",
    'Debug message level',
    None,
    u''))


## User code in "global" scope


print "All python PLC load globals variables: ", PLCGlobalsDesc
print "Current extention name: ", __ext_name__



## Beremiz python runtime calls
def _runtime_2_init():
    PLCGlobals.SIGNAL_NOT_CONNECT= 0b1111111111
    PLCGlobals.FILE_NOT_FOUND=     0b1111111110
    PLCGlobals.CLOSE_CSV_OK =      0b111111111
    PLCGlobals.CLOSE_CSV_FAIL =    0b111111110
    PLCGlobals.SAVE_CSV_OK =       0b11111111
    PLCGlobals.SAVE_CSV_FAIL =     0b11111110
    
    PLCGlobals.FILE_EOF = 0b1111111
    PLCGlobals.WRITE_OK = 0b111111
    PLCGlobals.WRITE_FAIL = 0b011111
    PLCGlobals.READ_OK = 0b11111
    PLCGlobals.READ_FAIL = 0b01111
    PLCGlobals.NEXT_OK=0b111
    PLCGlobals.NEXT_FAIL=0b011
    PLCGlobals.OPEN_DICT_OK = 0b11
    PLCGlobals.OPEN_DICT_FAIL = 0b01
    PLCGlobals.OPEN_CSV_OK = 0b1
    PLCGlobals.OPEN_CSV_FAIL = 0
    PLCGlobals.UPDATE_OK = 0b10
    PLCGlobals.UPDATE_FAIL = 0b01
    PLCGlobals.SET_VAL_OK = 0b10
    PLCGlobals.SET_VAL_FAIL = 0b01

def _runtime_2_cleanup():
    pass

def _runtime_2_start():
    pass

def _runtime_2_stop():
    pass



del __ext_name__

